# Generated by Django 5.1.5 on 2025-05-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_citizen", models.IntegerField(default=0)),
                (
                    "pourcentage_handicap",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=3),
                ),
                ("prioritized_citizen", models.IntegerField(default=0)),
            ],
        ),
    ]
