# Generated by Django 5.1.5 on 2025-05-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(default="Rakoto", max_length=100)),
                (
                    "email",
                    models.EmailField(default="citizen@gmail.com", max_length=100),
                ),
                ("contact", models.CharField(default="0385944903", max_length=10)),
                ("children", models.IntegerField(default=0)),
                ("job", models.CharField(default="Labor", max_length=100)),
                ("handicap", models.BooleanField(default=False)),
                ("income", models.IntegerField(default=0)),
            ],
        ),
    ]
