# Generated by Django 5.1.5 on 2025-05-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="status",
            field=models.CharField(default="Single", max_length=100),
        ),
    ]
