# Generated by Django 5.1.5 on 2025-05-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizen", "0002_citizen_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile", models.CharField(default="Prioritaire", max_length=100)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="citizen.citizen",
                    ),
                ),
            ],
        ),
    ]
