# Generated by Django 5.1.5 on 2025-05-01 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizen", "0003_profileclassification"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="citizen",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="profileclassification",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="profileclassification",
            name="update_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
