# Generated by Django 5.2 on 2025-05-02 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizen", "0004_citizen_created_at_citizen_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profileclassification",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.CharField(default="No activity", max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="citizen.citizen",
                    ),
                ),
            ],
        ),
    ]
