# Generated by Django 5.2 on 2025-05-02 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizen", "0005_rename_update_at_profileclassification_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="birthdate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
