# Generated by Django 5.2 on 2025-05-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizen", "0006_citizen_birthdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileclassification",
            name="priority",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
